### ISSUE TITLE
Bug in gamchanger.py

### ISSUE THREAD

**Issue by fsaforo1** [interpretml/gam-changer#10]
The demo `gam-changer-adult.ipynb` breaks because of the bug below:

```
[/usr/local/lib/python3.8/dist-packages/gamchanger/gamchanger.py](https://localhost:xxxx/#) in get_model_data(ebm, resort_categorical)
     71     score_range = [np.inf, -np.inf]
     72 
---> 73     for i in range(len(ebm.feature_names)):
     74         cur_feature = {}
     75         cur_feature["name"] = ebm.feature_names[i]

TypeError: object of type 'NoneType' has no len()
```

A potential quick fix would be to change `ebm.feature_names` to `ebm.term_names_`

**Comment by xiaohk** [comment]
Hello @fsaforo1, thanks for letting us know! Sorry, this error is due to some variable name inconsistency with `interpret v0.3.0` (#9). I will fix it when I get a chance (have been quite busy for some deadlines 😢). For now, you can use `interpret v0.2.7` with `gamchanger v0.1.10`.

**Comment by xiaohk** [comment]
Hi @fsaforo1, [GAM Changer `v0.1.12`](https://pypi.org/project/gamchanger/) should fix this error. You can upgrade your GAM Changer version with `pip install -U gamchanger`.
