### ISSUE TITLE
Support for new link fuctions

### ISSUE THREAD

**Issue by DaKlaas** [interpretml/gam-changer#11]
Hi there,
I see in the new version of interpretml (0.4.0), they just added new link functions for regression.
Will these also be added to gam-changer? 

Kind Regards
Klaas

**Comment by xiaohk** [comment]
Hi Klaas, do you mean these new objective functions: `poisson_deviance, tweedie_deviance, gamma_deviance, pseudo_huber, rmse_log`? I don't plan to add them to GAM Changer, but PRs are welcome and appreciated! Currently, the WebAssembly source code to apply link functions is [here](https://github.com/xiaohk/ebm.js/blob/562e13f126ecd171d89acc8412236f763f281975/assembly/ebm.ts#L253-L257).
