### ISSUE TITLE
AttributeError: 'ExplainableBoostingClassifier' object has no attribute 'histogram_counts_'

### ISSUE THREAD

**Issue by austin-rubin** [interpretml/gam-changer#12]
`gc.visualize(ebm, X_sample, y_sample)` results in an attribute error as shown in the following image:

![gam-changer attribute error](https://github.com/interpretml/gam-changer/assets/80716001/af296364-20af-4ac8-81e6-709cba2104e7)

This was ran on the provided Binder and Google Colab demo notebooks

**Comment by austin-rubin** [comment]
> #run this 
> `ebm.histogram_counts_ = ebm.bagged_scores_`
> 
> #gamchanger should now work 
> `gc.visualize(ebm, X_sample, y_sample) `

Thanks for the workaround, @serband !

I am not sure if it's only on my device, but have you also noticed that the density plot doesn't render?

GAMCHANGER on my device:
![gam_changer](https://github.com/interpretml/gam-changer/assets/80716001/5ee2d968-dcb5-4ec1-b4f9-2b87bcd3cfc4)

GAMCHANGER based on the repo's README:
![68747470733a2f2f692e696d6775722e636f6d2f654b7a4b4a666c2e706e67](https://github.com/interpretml/gam-changer/assets/80716001/1beff989-8f58-433f-8740-fc657c1f7853)

**Comment by xiaohk** [comment]
Thank you so much @austin-rubin and @serband!

`ebm.histogram_counts_ = ebm.bagged_scores_` is a nice try, but it should be `ebm.histogram_counts_ = ebm.histogram_weights`. 😂 Interpret changed the name `histogram_counts_` to `histogram_weights_` (and also int → float) in https://github.com/interpretml/interpret/commit/fe59c2f0da42bda98e1330ada5432b51b05f438a.

https://github.com/interpretml/gam-changer/commit/4b2194cdf02cce9754b3032a061cd3c586caff53 should fix it. @austin-rubin you can try to update `gamchanger` to 0.1.13, and the visualization should show up correctly. Let me me know if it doesn't work.

**Comment by xiaohk** [comment]
Awesome!! 🎉

**Comment by serband** [comment]
@austin-rubin  apologies for giving you the wrong answer! @xiaohk  Thank you for the quick fix!
