### ISSUE TITLE
pair_preprocessor_ is None 

### ISSUE THREAD

**Issue by esoreq** [interpretml/gam-changer#13]
First, thanks for adding this module - it is a great idea and a great contribution to transparent models. 
When running your code there seems to be an old (I think) mapping in line 430 in gamchanger.py 
`  # Use the ebm's mapping to map level name to bin index
    ebm_col_mapping = ebm_copy.pair_preprocessor_.col_mapping_`

I think this relates to earlier versions of EBM 
When I change this line to 
`ebm_col_mapping = ebm_copy.feature_groups_`     
The adjusted model is properly exported

**Comment by xiaohk** [comment]
Hi @esoreq, thanks for raising the issue. It seems you are looking at an older version of `gamchanger.py`? I made a lot of changes in https://github.com/interpretml/gam-changer/commit/093a6b6cc5147265d2fc54418ae42a56fe13fae6, and the lines you refer too seem to be different now.

https://github.com/interpretml/gam-changer/blob/aba94f624c726e63ef7360c5c691aedac3a44bd4/notebook-widget/gamchanger/gamchanger.py#L526-L527

Can you try to update `gamchanger` to the latest version (0.1.13) and try again? `pip install -U gamchanger`. Let me know if you still encounter an error. Thanks!!
