### ISSUE TITLE
inconsistent with package interpret

### ISSUE THREAD

**Issue by JiaxiangBU** [interpretml/gam-changer#9]
```python
import gamchanger as gc
from json import dump

# Extract model weights
model_data = gc.get_model_data(ebm)

# Generate sample data
sample_data = gc.get_sample_data(ebm, x_test, y_test)

# Save to `model.json` and `sample.json`
dump(model_data, open('./model.json', 'w'))
dump(sample_data, open('./sample.json', 'w'))
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-81-f99310b1230c> in <module>
      3 
      4 # Extract model weights
----> 5 model_data = gc.get_model_data(ebm)
      6 
      7 # Generate sample data

/conda/envs/notebook/lib/python3.6/site-packages/gamchanger/gamchanger.py in get_model_data(ebm, resort_categorical)
     71     score_range = [np.inf, -np.inf]
     72 
---> 73     for i in range(len(ebm.feature_names)):
     74         cur_feature = {}
     75         cur_feature["name"] = ebm.feature_names[i]

TypeError: object of type 'NoneType' has no len()
```

The object `ebm ` does not have the `feature_names` sub one.

Which version of `gamchanger` I can degrade?

```sh
%watermark -iv

gamchanger 0.1.10
numpy      1.18.0
interpret  0.3.0
pandas     1.0.4
```

**Comment by xiaohk** [comment]
Hello @JiaxiangBU, sorry about that! [`interpret v0.3.0`](https://github.com/interpretml/interpret/releases/tag/v0.3.0) introduced some name changes that the current GAM Changer is not compatible with.

For now you can downgrade `interpret` to `v0.2.7`. I will update GAM Changer to support the new names soon.

**Comment by JiaxiangBU** [comment]
> Hello @JiaxiangBU, sorry about that! [`interpret v0.3.0`](https://github.com/interpretml/interpret/releases/tag/v0.3.0) introduced some name changes that the current GAM Changer is not compatible with.
> 
> For now you can downgrade `interpret` to `v0.2.7`. I will update GAM Changer to support the new names soon.

I find when I install `interpret` the depends `interpret-core` is automatically installed. And it works using `pip install interpret-core==0.2.7`

**Comment by xiaohk** [comment]
Hi @JiaxiangBU, [GAM Changer `v0.1.12`](https://pypi.org/project/gamchanger/) should fix this error. You can try it out with `pip install -U gamchanger`.
